name: Build and Release IPK

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
      title:
        description: 'Release title'
        required: true
      target:
        description: 'OpenWrt SDK Git URL'
        default: 'https://github.com/openwrt/sdk.git'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget

      - name: Clone OpenWrt SDK
        run: |
          git clone --depth=1 ${{ github.event.inputs.target }} sdk

      - name: Add luci-app-nfttl to OpenWrt SDK
        run: |
          mkdir -p sdk/package/custom
          cp -r luci-app-nfttl sdk/package/custom/luci-app-nfttl

      - name: Build luci-app-nfttl
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make package/custom/luci-app-nfttl/compile V=s

      - name: Upload .ipk to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.title }}
          files: |
            sdk/bin/packages/*/*/luci-app-nfttl_*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
