name: Build and Release OpenWrt Package

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger the workflow on
    tags:
      - 'v*'  # Triggers on version tags like v1.0, v1.1, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up OpenWrt Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-venv python3-pip rsync unzip zlib1g-dev file wget

          # Attempt to install python3-distutils
          sudo apt-get install -y python3-distutils || echo "python3-distutils not found, continuing..."

          # Install or upgrade setuptools
          python3 -m pip install --upgrade setuptools

          # If distutils isn't available, we try to install it from pip
          python3 -m pip install distutils || echo "distutils not available via pip, continuing..."

      - name: Set up OpenWrt repository (24.10.0)
        run: |
          # Clone OpenWrt into a directory with write permissions
          mkdir -p $HOME/openwrt
          git clone https://github.com/openwrt/openwrt.git $HOME/openwrt
          cd $HOME/openwrt
          git checkout openwrt-24.10  # Set OpenWrt version to v24.10.0

      - name: Copy package to OpenWrt feed directory
        run: |
          cp -R luci-app-nfttl $HOME/openwrt/package/

      - name: Install OpenWrt build dependencies
        run: |
          cd $HOME/openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: Build the OpenWrt package
        run: |
          cd $HOME/openwrt
          make package/luci-app-nfttl/compile V=s

      - name: Upload IPK to GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: $HOME/openwrt/bin/packages/*/luci-app-nfttl*.ipk

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload IPK to GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: $HOME/openwrt/bin/packages/*/luci-app-nfttl*.ipk
