name: Manual Build and Release

on:
  workflow_dispatch:  # Enables the "Run workflow" button in GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget python3

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/qualcommax/ipq807x/openwrt-sdk-23.05.3-qualcommax-ipq807x_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* sdk

      - name: Copy luci-app-nfttl to SDK
        run: |
          mkdir -p sdk/package/luci-app-nfttl
          cp -r luci-app-nfttl/* sdk/package/luci-app-nfttl/

      - name: Build luci-app-nfttl
        working-directory: sdk
        run: |
          make defconfig
          make package/luci-app-nfttl/compile V=s

      - name: Find built IPK
        id: find_ipk
        run: |
          IPK=$(find sdk/bin/packages/ -name 'luci-app-nfttl_*.ipk' | head -n 1)
          echo "ipk_path=$IPK" >> "$GITHUB_OUTPUT"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.find_ipk.outputs.ipk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
